Projet2Crowdfunding/ViewModels/PaymentViewModel.cs
using System;
using Projet2Crowdfunding.Models;

namespace Projet2Crowdfunding.ViewModels
{
    public class PaymentViewModel
    {
        

        public double Amount { get; set; }
        public Donation Donation { get; set; }
        public Account Account { get; set; }
        public Participant Participant { get; set; }
        public Project Project { get; set; }
        public bool Authentify { get; set; }

      
    }
}

Projet2Crowdfunding/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using HtmlAgilityPack;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Projet2Crowdfunding.Models;
using Projet2Crowdfunding.Service;
using Projet2Crowdfunding.ViewModels;
using Stripe;
using Stripe.Checkout;
using AccountService = Projet2Crowdfunding.Service.AccountService;

namespace Projet2Crowdfunding.Controllers
{
    public class PaymentsController : Controller
    {
        PaymentService paymentService;
        AccountService accountService;
        ProjectService projectService;
        private IWebHostEnvironment _env;

        public PaymentsController(IWebHostEnvironment environment)
            
        {
            paymentService = new PaymentService();
            accountService = new AccountService();
            projectService = new ProjectService();
            _env = environment;
            StripeConfiguration.ApiKey = "sk_test_51KUbEVFZdOzBn1VnNLVh8lPPu6fTUDUrkMOS7lOremlO7jGBkZg54ArHR0wd3tRAQTtfYmRUGZ0xJmSMkF0RX6iV00nrUzdcIC";
        }
        
        [HttpPost]
        public IActionResult CreateCheckoutSession(PaymentViewModel viewModel) 

        {
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {

                            UnitAmount = (long?)(viewModel.Amount*100),
                            Currency = "eur",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = "Contribution",
                            },

                        },
                        Quantity = 1,
                    },
                },
                Mode = "payment",
                SuccessUrl = "http://localhost:5000/Payments/PaymentSuccess",
                CancelUrl = "http://localhost:5000/Home/Index",
            };
            
            var service = new SessionService();
            Session session = service.Create(options);

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        public IActionResult PaymentPage()
        {
            BddContext ctx = new BddContext();

            PaymentViewModel viewModel = new PaymentViewModel { Authentify = HttpContext.User.Identity.IsAuthenticated }; //cookies
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
                viewModel.Participant = accountService.GetParticipantFromAccountId(viewModel.Account.Id);
            }
            return View(viewModel);
        }
      

        public IActionResult ProjectPaymentPage(int? id)
        {
            BddContext ctx = new BddContext();
                       
            PaymentViewModel viewModel = new PaymentViewModel { Authentify = HttpContext.User.Identity.IsAuthenticated }; //cookies

            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
                viewModel.Participant = accountService.GetParticipantFromAccountId(viewModel.Account.Id);
            }
            viewModel.Project = ctx.Projects.Find(id);
            return View(viewModel);
        }

        public IActionResult PaymentSuccess()
        {
            BddContext ctx = new BddContext();

            PaymentViewModel viewModel = new PaymentViewModel { Authentify = HttpContext.User.Identity.IsAuthenticated }; //cookies
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
                viewModel.Participant = accountService.GetParticipantFromAccountId(viewModel.Account.Id);
            }
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult CreateCheckoutSession2(int? id, PaymentViewModel viewModel)
        {
            double amount = viewModel.Amount;
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {

                        UnitAmount = (long?)amount * 100,
                        Currency = "eur",
                          ProductData = new SessionLineItemPriceDataProductDataOptions
                          {
                            Name = "Contribution",
                          },

                    },
                    Quantity = 1,
                },
            },
            Mode = "payment",
            SuccessUrl = "http://localhost:5000/Payments/PaymentSuccess",
            CancelUrl = "http://localhost:5000/Home/Index",
            };

            var service = new SessionService();
            Session session = service.Create(options);

            viewModel = new PaymentViewModel { Authentify = HttpContext.User.Identity.IsAuthenticated }; //cookies

            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
                viewModel.Participant = accountService.GetParticipantFromAccountId(viewModel.Account.Id);
                viewModel.Project = projectService.GetProject(id);
            }
            paymentService.CreateDonation(id,viewModel.Participant.Id, amount );

            //Envoie Mail
            using (MailMessage mm = new MailMessage("macssynergy@gmail.com", viewModel.Account.Mail))
            {
                mm.Subject = "Facture de votre Donnation sur MACSynergy";
                mm.Body = "Bonjour Mr/Mme " + viewModel.Participant.LastName + ",\n\n" +
                    "Merci pour votre contribution au projet !! \n\n" +
                    "Vous trouverez ci-dessous le récapitulatif de votre donation.\n\n" +
                    "Nom du project : " + viewModel.Project.Name + " \n" +
                    "Date de clôture du project : " + viewModel.Project.EndDate.ToString("dd/MM/yyyy") + " \n" +
                    "Montant donné : " + amount + " € \n\n\n" +
                    "A bientôt sur MACSynergy!";

                mm.Attachments.Add(new System.Net.Mail.Attachment(_env.ContentRootPath + "/wwwroot/Images/logoMacSynergy.png"));

                mm.IsBodyHtml = false;

                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential("macssynergy@gmail.com", "Macsynergy4");
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mm);
                }
            }

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

    }
}

Projet2Crowdfunding/Views/Payments/PaymentPage.cshtml
@model Projet2Crowdfunding.ViewModels.PaymentViewModel

@{
    Layout = "_LayoutDuSite";

}


<link rel="stylesheet" type="text/css" href="~/css/Home.css">


<style>
    .accordion {
        background-color: #eee;
        color: #444;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        text-align: left;
        border: none;
        outline: none;
        transition: 0.4s;
    }


        .active, .accordion:hover {
            background-color: #ccc;
        }


    .panel {
        padding: 0 18px;
        background-color: white;
        display: none;
        overflow: hidden;
    }
</style>


@section Menu
{
    @if (Model.Authentify)
    {
        if (Model.Account.Role == "participant")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Participant/PDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else if (Model.Account.Role == "po")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/ProjectOwner/PODashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else // role == "admin"
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Admin/AdminDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
    }
    else
    {
        <div class="col-md-8 d-flex justify-content-around">
            <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
            <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
            <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
        </div>
        <div class="col-md-2 d-flex justify-content-end align-items-center">
            <a id="bouton-log" href="/Account/LoginPage">SE CONNECTER</a>
        </div>
    }
}




<div class="container d-flex justify-content-center mt-5 mb-5">
    <div class="row g-3" style="width:600px;">
        <div class="col-md-12">

            @using (Html.BeginForm("CreateCheckoutSession", "Payments", FormMethod.Post))
            {
                <h2> Montant de participation</h2>
                @Html.TextBoxFor(model => model.Amount)
                @*<input type="text" class="form-control" placeholder="Saisir le montant">*@
                <br />
                <br />
                <br />
                <br />

                <button id="bouton-log" type="submit">PAIEMENT</button>


            }
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />

            @*<div class="col-md-6">*@
            <!--<h2>Méthodes de paiement</h2>-->
            @*</div>*@
            <!--</div>
            <div class="row g-3">
                <div class="col-md-12">
                    <button class="accordion mb-3 btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <span>Paypal</span> <img src="https://i.imgur.com/7kQEsHU.png" width="30">
                    </button>
                    <div class="panel">
                        <span class="font-weight-normal card-text">Adresse e-mail</span>
                        <br />
                        <div class="input"> <input type="text" class="form-control" placeholder="kevindurand@hotmail.com"> </div>
                        <br />
                        <bouton id="bouton-log" type="submit">VALIDER</bouton>
                        <br />
                        <br />
                    </div>
                </div>
            </div>
            <div class="row g-3">
                <div class="col-md-12">
                    <button class="accordion btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <span>Carte de crédit</span> <img src="https://i.imgur.com/2ISgYja.png" width="30">
                    </button>

                    <div class="panel">
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body payment-card-body">


                                <span class="font-weight-normal card-text">Numéro de la carte</span>
                                <div class="input"> <i class="fa fa-credit-card"></i> <input type="text" class="form-control" placeholder="0000 0000 0000 0000"> </div>
                                <div class="row mt-3 mb-3">
                                    <div class="col-md-9">
                                        <span class="font-weight-normal card-text">Date d'expiration</span>
                                        <div class="input"> <i class="fa fa-calendar"></i> <input type="text" class="form-control" placeholder="MM/YY"> </div>
                                        <span class="font-weight-normal card-text">Nom du titulaire</span>
                                        <div class="input"> <i class="fa fa-user"></i> <input type="text" class="form-control" placeholder="Kevin DURAND"> </div>
                                    </div>
                                    <div class="col-md-9">
                                        <span class="font-weight-normal card-text">CVV</span>
                                        <div class="input"> <i class="fa fa-lock"></i> <input type="text" class="form-control" placeholder="000"> </div>
                                        <br />
                                    </div>
                                    <div class="col-md-9">

                                        <bouton id="bouton-log" type="submit">VALIDER</bouton>
                                        <br />

                                    </div>

                                </div> <span class="text-muted certificate-text"><i class="fa fa-lock"></i> Votre transaction est sécurisée avec le certificat ssl</span>
                            </div>
                        </div>
                    </div>
                </div>-->
        </div>
    </div>
</div>



@section Footer {}


<!--<script>var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function () {
        this.classList.toggle("active");

        var panel = this.nextElementSibling;
        if (panel.style.display === "block") {
            panel.style.display = "none";
        } else {
            panel.style.display = "block";
        }
    });
}</script>-->

Projet2Crowdfunding/Views/Payments/PaymentSuccess.cshtml
@model Projet2Crowdfunding.ViewModels.PaymentViewModel

@{ Layout = "_LayoutDuSite"; }


<link rel="stylesheet" type="text/css" href="~/css/Home.css">




@section Menu
{
    @if (Model.Authentify)
    {
        if (Model.Account.Role == "participant")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Participant/PDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else if (Model.Account.Role == "po")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/ProjectOwner/PODashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else // role == "admin"
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Admin/AdminDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
    }
    else
    {
        <div class="col-md-8 d-flex justify-content-around">
            <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
            <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
            <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
        </div>
        <div class="col-md-2 d-flex justify-content-end align-items-center">
            <a id="bouton-log" href="/Account/LoginPage">SE CONNECTER</a>
        </div>
    }
}


<br />
<br />
<div class="container container-fluid" align="center">
    
        <div class="row">
            <div class="col-sm-3">
                </div>
                <div class="col-sm-6">
                    
                    <p style="font-size: 20px; font-style: italic; font-weight: 600; align-content: center; text-align: center">NOUS VOUS REMERCIONS POUR VOTRE PARTICIPATION! :)</p>
                    <br />
                    <p style="font-size: 16px; font-style: italic; align-content:center; text-align:center">
                        Contactez-nous si vous avez besoin de plus d'informations
                        <br />
                        <br />
                    </p>

                    <a class="nav-link" id="nav-active" href="/Home/Index"><strong>Retour à la page d'accueil SVP</strong></a>
                    <br />
                    <br />
                    <br />

                    <img style="width:60%;" src="~/Images/donation.jpg" alt="" /><img />
                </div>
                <div class="col-sm-3">
                 </div>

            

         </div>


    <br />
    <br />





    @section Footer {}



Projet2Crowdfunding/Views/Payments/ProjectPaymentPage.cshtml
    @model Projet2Crowdfunding.ViewModels.PaymentViewModel

    @{ Layout = "_LayoutDuSite"; }

    <link rel="stylesheet" type="text/css" href="~/css/Home.css">

@section Menu
{
    @if (Model.Authentify)
    {
        if (Model.Account.Role == "participant")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Participant/PDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else if (Model.Account.Role == "po")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/ProjectOwner/PODashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else // role == "admin"
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Admin/AdminDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
    }
    else
    {
        <div class="col-md-8 d-flex justify-content-around">
            <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
            <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
            <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
        </div>
        <div class="col-md-2 d-flex justify-content-end align-items-center">
            <a id="bouton-log" href="/Account/LoginPage">SE CONNECTER</a>
        </div>
    }
}


    <div class="container d-flex justify-content-center mt-5 mb-5">
        <div class="row g-3" style="width:600px;">
            <div class="col-md-12">
                <h2> Montant de participation</h2>


                @{string pagelink2 = "/Payments/CreateCheckoutSession2/" + @Model.Project.Id;}
            <form method="post" action="@pagelink2">
                @Html.TextBoxFor(model => model.Amount)
                <br />
                <br />
                <br />
                <br />
                <button id="bouton-log" type="submit">Paiement</button>
            </form>
               
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>



    @section Footer {}