Projet2Crowdfunding/Models/ProjectOwner.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Projet2Crowdfunding.Models
{
    public enum ProjectOwnerType { Association, ONG}
    public enum AssoStatus { registered, published, rejected}

    public class ProjectOwner
    {
        public int Id { get; set; }

        [MaxLength(15)]
        [Required]
        [Display(Name = "Numéro de téléphone")]
        public string PhoneNumber { get; set; }

        [MaxLength(45)]
        [Required]
        [Display(Name = "Nom de l'organisation")]
        public string Name { get; set; }

        [Column(TypeName= "text")]
        [Required]
        [Display(Name = "Résumé de l'organisation")]
        public string Summary { get; set; }

        [Column(TypeName = "text")]
        [Display(Name = "Description de l'organisation")]
        public string Description { get; set; }

        [MaxLength(100)]
        [Display(Name = "Lien Hypertext")]
        public string HyperLink { get; set; }

        [Column(TypeName = "text")]
        [Display(Name = "Description volontariat")]
        public string VolunteerDescritpion { get; set; }

        [MaxLength(300)]
        [Display(Name = "Partenariat")]
        public string Partnership { get; set; }

        [Required]
        public ProjectOwnerType Type { get; set; }

        [MaxLength(250)]
        [Required]
        [Display(Name = "Justificatif de l'organisation")]
        public string AssociationProof { get; set; }

        [MaxLength(250)]
        [Display(Name = "Logo")]
        public string Image { get; set; }

        [Required]
        [Display(Name = "État")]
        public AssoStatus Status { get; set; }

        [Required]
        [Display(Name = "Charte de Confidentialité")]
        public Boolean ConfidentialityCharter { get; set; }

        public Boolean Newsletter { get; set; }

        [Required]
        [Display(Name = "Adresse")]
        public int? AddressId { get; set; }
        public virtual Address Address { get; set; }

        [Required]
        public int? AccountId { get; set; }
        public virtual Account Account { get; set; }

    }
}

Projet2Crowdfunding/Controllers/ProjectOwnerController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projet2Crowdfunding.Models;
using Projet2Crowdfunding.Service;
using Projet2Crowdfunding.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Projet2Crowdfunding.Controllers
{
    public class ProjectOwnerController : Controller
    {
        private AccountService accountService;
        private ProjectService projectService;
        private CreateProjectService createProjectService;
        private IWebHostEnvironment _env;

        public ProjectOwnerController(IWebHostEnvironment environment)
        {
            accountService = new AccountService();
            projectService = new ProjectService();
            createProjectService = new CreateProjectService();
            _env = environment;
        }

        public IActionResult PODashboard()
        {
            AccountViewModel viewModel = new AccountViewModel { Authentify = HttpContext.User.Identity.IsAuthenticated }; //cookies
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
                viewModel.ProjectOwner = accountService.GetProjectOwnerFromAccountId(viewModel.Account.Id);
                viewModel.ProjectList = projectService.GetProjectsFromProjectOwnerId(viewModel.ProjectOwner.Id);
                viewModel.CollectionList = projectService.GetAllCollections();
                return View(viewModel);
            }
            
            return View(viewModel);
        }


        public IActionResult POPage(int? id)
        {
            AccountViewModel viewModel = new AccountViewModel { Authentify = HttpContext.User.Identity.IsAuthenticated }; //cookies
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
            }
            if (id.HasValue)
            {
                viewModel.ProjectOwner = accountService.GetProjectOwner(id.Value);
                viewModel.ProjectOwner.Account = accountService.GetAccount((int)viewModel.ProjectOwner.AccountId);
                viewModel.ProjectList = projectService.GetProjectsFromPOIdStatus(id.Value, Status.Publié);
            }
            return View(viewModel);
            
        }

        public IActionResult ModifyProjectOwner(int Id)
        {
            if (Id != 0)
            {
                BddContext ctx = new BddContext();
                ProjectOwner projectOwner = ctx.ProjectOwners.Find(Id);
                if (projectOwner == null)
                {
                    return View("Error");
                }
                return View(projectOwner);
            }
            return View("Error");
        }

        [HttpPost]
        public IActionResult ModifyProjectOwnerInfos(ProjectOwner projectOwner)
        {
            if (projectOwner.Id != 0)
            {
                ProjectOwnerService ps = new ProjectOwnerService();
                ps.ModifyProjectOwnerInfos(projectOwner.Id, projectOwner.Name, projectOwner.Type,
                    projectOwner.HyperLink);
                return RedirectToAction("PODashboard");
            }
            else
            {
                return View("Error");
            }
        }

        public IActionResult ModifyProjectOwnerAddress(ProjectOwner projectOwner)
        {
            if (projectOwner.Id != 0)
            {
                ProjectOwnerService ps = new ProjectOwnerService();
                ps.ModifyProjectOwnerAddress(projectOwner.Id, projectOwner.Address.StreetNumber, projectOwner.Address.StreetName, projectOwner.Address.ZipCode,
                    projectOwner.Address.City, projectOwner.Address.Country);
                return RedirectToAction("PODashboard");
            }
            else
            {
                return View("Error");
            }
        }

        public IActionResult ModifyProjectOwnerPhone(ProjectOwner projectOwner)
        {
            if (projectOwner.Id != 0)
            {
                ProjectOwnerService ps = new ProjectOwnerService();
                ps.ModifyProjectOwnerPhone(projectOwner.Id, projectOwner.PhoneNumber);
                return RedirectToAction("PODashboard");
            }
            else
            {
                return View("Error");
            }
        }

        public IActionResult ModifyProjectOwnerDescription(ProjectOwner projectOwner)
        {
            if (projectOwner.Id != 0)
            {
                ProjectOwnerService ps = new ProjectOwnerService();
                ps.ModifyProjectOwnerDescription(projectOwner.Id, projectOwner.Summary, projectOwner.Description, projectOwner.VolunteerDescritpion, projectOwner.Partnership);
                return RedirectToAction("PODashboard");
              }
            else
            {
                return View("Error");
            }
        }

        public IActionResult ModifyProjectOwnerLogo(AccountViewModel viewModel, IFormFile AssoLogo)
        {            
            string fileName = "";
            if (viewModel.AssoLogo != null)
            {
                fileName = Path.GetFileName(viewModel.AssoLogo.FileName);
                var filePath = _env.ContentRootPath + "\\wwwroot\\ImageAssos";
                using (var fileSteam = new FileStream(Path.Combine(filePath, fileName), FileMode.Create))
                {
                    viewModel.AssoLogo.CopyTo(fileSteam);
                }
            }

            if (viewModel.ProjectOwner.Id != 0)
            {
                ProjectOwnerService ps = new ProjectOwnerService();
                ps.ModifyProjectOwnerLogo(viewModel.ProjectOwner.Id, fileName);
                return RedirectToAction("PODashboard");
            }
            else
            {
                return View("Error");
            }
        }


        public IActionResult ModifyProject()
        {
            AccountViewModel viewModel = new AccountViewModel { Authentify = HttpContext.User.Identity.IsAuthenticated }; //cookies
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
                viewModel.ProjectOwner = accountService.GetProjectOwnerFromAccountId(viewModel.Account.Id);
                viewModel.Project = accountService.GetProjectFromProjectOwnerId(viewModel.ProjectOwner.Id);
                List<Step> steps = projectService.GetStepsFromProjectId(viewModel.Project.Id);
                viewModel.Step1 = steps[0];
                viewModel.Step2 = new Step();
                viewModel.Step3 = new Step();
                if (steps.Count() > 1)
                {
                    viewModel.Step2 = steps[1];
                }
                if (steps.Count() > 2)
                {
                    viewModel.Step3 = steps[2];
                }

                return View(viewModel);
            }

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult ModifyProject(int? id, AccountViewModel viewModel, IFormFile Picture)
        {
            string fileNameImage = "";
            //string fileNameVideo = "";
            viewModel.Authentify = HttpContext.User.Identity.IsAuthenticated; //cookies
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Account = accountService.GetAccount(HttpContext.User.Identity.Name);
                viewModel.ProjectOwner = accountService.GetProjectOwnerFromAccountId(viewModel.Account.Id);               
            }

            if (viewModel.Project.Name != null && viewModel.Project.Summary != null &&
                viewModel.Project.Descritpion != null && viewModel.Project.Category != null &&
                viewModel.Project.Location != null && viewModel.Project.EndDate != null &&
                viewModel.Step1.Amount != 0 && viewModel.Step1.Description != null)
            {
                if (viewModel.ProjectImage != null)
                {
                    fileNameImage = Path.GetFileName(viewModel.ProjectImage.FileName);
                    var filePath = _env.ContentRootPath + "\\wwwroot\\ImagesProject";
                    using (var fileSteam = new FileStream(Path.Combine(filePath, fileNameImage), FileMode.Create))
                    {
                        viewModel.ProjectImage.CopyTo(fileSteam);
                    }
                }

                //if (viewModel.ProjectVideo != null)
                //{
                //    fileNameVideo = Path.GetFileName(viewModel.ProjectVideo.FileName);
                //    var filePath = _env.ContentRootPath + "\\wwwroot\\VideosProject";
                //    using (var fileSteam = new FileStream(Path.Combine(filePath, fileNameVideo), FileMode.Create))
                //    {
                //        viewModel.ProjectVideo.CopyTo(fileSteam);
                //    }
                //}

                createProjectService.ModifyProject(id, viewModel.Project.Name,
                    viewModel.Project.Summary, viewModel.Project.Descritpion, viewModel.Project.Category,
                    viewModel.Project.Location, viewModel.Project.EndDate, fileNameImage, viewModel.Project.Video,
                    viewModel.Project.MaterialDonation, viewModel.Step1.Amount, viewModel.Step1.Description,
                    viewModel.Step2.Amount, viewModel.Step2.Description, viewModel.Step3.Amount, viewModel.Step3.Description);

                var userClaims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier, viewModel.Account.Mail),

Projet2Crowdfunding/Views/ProjectOwner/ModifyProject.cshtml
@model Projet2Crowdfunding.ViewModels.AccountViewModel
@{
    Layout = "_LayoutDuSite";

}
<link rel="stylesheet" type="text/css" href="~/css/Login.css">
<link rel="stylesheet" type="text/css" href="~/css/Home.css">

<title>Inscription porteur de projet</title>




@section Menu
{
    @if (Model.Authentify)
    {
        if (Model.Account.Role == "participant")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Participant/PDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else if (Model.Account.Role == "po")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/ProjectOwner/PODashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else // role == "admin"
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Admin/AdminDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
    }
    else
    {
        <div class="col-md-8 d-flex justify-content-around">
            <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
            <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
            <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
        </div>
        <div class="col-md-2 d-flex justify-content-end align-items-center">
            <a id="bouton-log" href="/Account/LoginPage">SE CONNECTER</a>
        </div>
    }
}




@if (Model.Authentify)
{
    if (@Model.Account.Role == "po")
    {

        <div class="my-5">
            <fieldset style="width : 1000px; margin:auto">

                <div class="mode-vert">
                    <h6 style="font-size: 30px; color:dimgray">MODIFIER LE PROJET</h6>
                    <br />
                </div>



                @using (Html.BeginForm("ModifyProject", "ProjectOwner", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    <div class="border-MACS mode-vert pt-1 p-lg-5 pr-5 pb-5">

                        <h6 style="font-size: 26px; text-align: left">CHAMPS REQUIS</h6>

                        <br /><br />

                        @Html.LabelFor(model => model.Project.Name) <span> &nbsp;</span>
                        @Html.TextBoxFor(model => model.Project.Name)

                        <br /><br />

                        @Html.LabelFor(model => model.Project.Summary) <br />
                        @Html.TextAreaFor(model => model.Project.Summary, new { @cols = "80", @rows = "4" })

                        <br /><br />

                        @Html.LabelFor(model => model.Project.Descritpion) <br />
                        @Html.TextAreaFor(model => model.Project.Descritpion, new { @cols = "80", @rows = "8" })

                        <br /><br />

                        @Html.LabelFor(model => model.Project.Category) <span> : </span> <br />
                        <span>Animaux </span> @Html.RadioButtonFor(model => model.Project.Category, "Animaux") <span>&nbsp;</span>
                        <span>Environnement </span> @Html.RadioButtonFor(model => model.Project.Category, "Environnement") <span>&nbsp;</span>
                        <span>Humanitaire </span> @Html.RadioButtonFor(model => model.Project.Category, "Humanitaire") <span>&nbsp;</span>
                        <span>Education</span> @Html.RadioButtonFor(model => model.Project.Category, "Education") <span>&nbsp;</span>
                        <span>Santé </span> @Html.RadioButtonFor(model => model.Project.Category, "Santé") <span>&nbsp;</span>
                        <span>Besoins Elémentaires </span> @Html.RadioButtonFor(model => model.Project.Category, "BesoinsElémentaires") <span>&nbsp;</span>
                        <span>Autre </span> @Html.RadioButtonFor(model => model.Project.Category, "Autre")

                        <br /><br />

                        @Html.LabelFor(model => model.Project.Location) <span> &nbsp;</span>
                        @Html.TextBoxFor(model => model.Project.Location)

                        <br /><br />

                        @Html.LabelFor(model => model.Project.EndDate) <span> &nbsp;</span>
                        @Html.TextBoxFor(model => model.Project.EndDate, new { type = "date" })


                        <div>

                            <br /><br />

                            <p style="color:dimgray">
                                PALIERS PROPOSES (
                                <span style="color: rgb(173, 209, 42); font-weight: 500;">Uniquement le prèmier palier est obligatoire</span>
                                )
                            </p>

                            <div class="container">

                                <div class="row">
                                    <div class="col-md-3">
                                        @Html.LabelFor(model => model.Step1.Amount) <br />
                                        @Html.TextBoxFor(model => model.Step1.Amount)
                                    </div>
                                    <div class="col-md-8">
                                        @Html.LabelFor(model => model.Step1.Description) <br />
                                        @Html.TextAreaFor(model => model.Step1.Description, new { @cols = "70", @rows = "4" })
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-3 pe-3">
                                        @Html.LabelFor(model => model.Step2.Amount) <br />
                                        @Html.TextBoxFor(model => model.Step2.Amount)
                                    </div>
                                    <div class="col-md-8">
                                        @Html.LabelFor(model => model.Step2.Description) <br />
                                        @Html.TextAreaFor(model => model.Step2.Description, new { @cols = "70", @rows = "4" })
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-3 pe-3">
                                        @Html.LabelFor(model => model.Step3.Amount) <br />
                                        @Html.TextBoxFor(model => model.Step3.Amount)
                                    </div>
                                    <div class="col-md-8">
                                        @Html.LabelFor(model => model.Step3.Description) <br />
                                        @Html.TextAreaFor(model => model.Step3.Description, new { @cols = "70", @rows = "4" })
                                    </div>
                                </div>

                            </div>

                        </div>


                        <br />

                        <div class="text-danger mt-4">
                            @Html.ValidationMessageFor(model => model.Project)
                        </div>

                    </div>


                    <br /><br />

                    <div class="border-MACS mode-vert pt-1 p-lg-5 pr-5 pb-5">

                        <h6 style="font-size: 26px; text-align: left">CHAMPS NON REQUIS</h6>

                        <br /><br />

                        @Html.LabelFor(model => model.ProjectImage) <span>&nbsp;</span>
                        @Html.TextBoxFor(model => model.ProjectImage, new { type = "file" })

                        <br /><br />

                        @Html.LabelFor(model => model.Project.Video) <span>&nbsp;</span>
                        @Html.TextBoxFor(model => model.Project.Video)

                        <br /><br />

                        @Html.LabelFor(model => model.Project.MaterialDonation) <br />
                        @Html.TextAreaFor(model => model.Project.MaterialDonation, new { @cols = "80", @rows = "8" })

                    </div>

                    <br /><br />

                    <button id="bouton-log" type="submit">MODIFIER</button><span>&nbsp;&nbsp;&nbsp;&nbsp;</span>

                    <a id="bouton-log" href="/ProjectOwner/CancelModify">ANNULER</a>

                }

            </fieldset>
        </div>

    }
    else
    {

        <div>
            <p style="font-size: 16px; color:dimgray">VEUILLEZ VOUS CONNECTER EN TANT QUE PORTEUR DE PROJET POUR LANCER VOTRE PROJET</p>
            <a href="/Account/LoginPage" class="hyperlink2">Cliquer ici pour se connecter</a>
        </div>

        <div>
            <p style="font-size: 16px; color:dimgray">Envie de publier votre projet sur MACSynergie?</p>
            <a href="/Account/PPInscription" class="hyperlink2">Inscrivez-vous en tant que Porteur de Projet!</a>
        </div>

    }

}
else
{

    <div class="m-5 p-5">
        <a href="/Account/LoginPage" class="hyperlink2" style="font-size: 20px; font-weight: 600;">VEUILLEZ VOUS CONNECTER EN TANT QUE PORTEUR DE PROJET POUR LANCER VOTRE PROJET</a>
    </div>

    <div class="mx-5 mb-5 px-5 pb-5">
        <p style="font-size: 20px; color:dimgray">Envie de publier votre projet sur MACSynergie?</p>
        <a href="/Account/PPInscription" class="hyperlink2" style="font-weight: 600;">Inscrivez-vous en tant que Porteur de Projet!</a>
    </div>

}


@section Footer {}

Projet2Crowdfunding/Views/ProjectOwner/POPage.cshtml
@model Projet2Crowdfunding.ViewModels.AccountViewModel
@{
    Layout = "_LayoutDuSite";
}


<link rel="stylesheet" type="text/css" href="~/css/Home.css">
<link rel="stylesheet" type="text/css" href="~/css/Login.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>



<title>Associations et ONGs</title>



@section Menu
{
    @if (Model.Authentify)
    {
        if (Model.Account.Role == "participant")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Participant/PDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else if (Model.Account.Role == "po")
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/ProjectOwner/PODashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
        else // role == "admin"
        {
            <div class="col-md-8 d-flex justify-content-around">
                <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
                <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
                <a class="nav-link" id="nav-elements" href="/Admin/AdminDashboard"><strong>MON COMPTE</strong></a>
            </div>
            <div class="col-md-2 d-flex justify-content-end align-items-center">
                <a id="bouton-log" href="/Account/Deconnexion">SE DECONNECTER</a>
            </div>
        }
    }
    else
    {
        <div class="col-md-8 d-flex justify-content-around">
            <a class="nav-link" id="nav-elements" href="/Home/Index"><strong>ACCUEIL</strong></a>
            <a class="nav-link" id="nav-elements" href="/Project/Index"><strong>DECOUVRIR UN PROJET</strong></a>
            <a class="nav-link" id="nav-elements" href="/CreateProject/Index"><strong>LANCER UN PROJET</strong></a>
        </div>
        <div class="col-md-2 d-flex justify-content-end align-items-center">
            <a id="bouton-log" href="/Account/LoginPage">SE CONNECTER</a>
        </div>
    }
}



<div class="container mt-5">
    <div class="row">
        <div class="col-sm-7">

            <div class="border-MACS">

                <div class="mode-vert pt-4 px-4">
                    <h6 style="font-size: 30px; color: rgb(63, 63, 63)">@Model.ProjectOwner.Name</h6>
                    <p style="font-size: 14px">@Model.ProjectOwner.Summary</p>
                </div>

                <div class="pb-4 px-4">
                    <img src="@Model.ProjectOwner.Image" alt="Flood" class="d-block" style="width:100%; margin: auto;">
                </div>

                <div class="pb-4 px-4">
                    @if (@Model.ProjectOwner.HyperLink != null)
                    {
                        <span style="font-size: 14px; color: dimgrey; font-weight: 500;">Pour plus d'information : </span>
                        <a href="@Model.ProjectOwner.HyperLink" class="hyperlink2" style="font-weight: 600;">@Model.ProjectOwner.HyperLink</a>
                        <br /><br />
                    }

                    @if (@Model.ProjectOwner.Partnership != null)
                    {
                        <p style="font-size: 14px"><span style="color:dimgrey; font-weight:500;">Nos partenaires : </span> @Model.ProjectOwner.Partnership</p>
                    }

                </div>

            </div>
        </div>

        <div class="col-sm-5">

            <div class="mode-vert ms-3">
                <h6 style="font-size: 30px;">Description de l'organisation</h6>
                <p style="font-size: 14px">@Model.ProjectOwner.Description</p>
            </div>

        </div>

    </div>
</div>


@if (@Model.ProjectOwner.VolunteerDescritpion != null)
{
    <div class="container mt-5" id="contactUs">
        <div class="row">

            <div class="mode-vert px-4">
                <h6 style="font-size: 30px">Voulez vous participer avec notre organisation ?</h6>
                <p style="font-size: 14px">@Model.ProjectOwner.VolunteerDescritpion</p>

                <button class="accordion hyperlink2" style="font-weight: 600;">Nous contacter</button>
                <div class="panel">
                    <p style="font-size: 14px">Email : @Model.ProjectOwner.Account.Mail</p>
                    <p style="font-size: 14px">Télephone : @Model.ProjectOwner.PhoneNumber</p>
                </div>

            </div>

        </div>
    </div>
}
<br />

<h6 class="pb-3 pt-4 d-flex justify-content-center align-items-center titre-carousel">
    ---------------------------- NOS PROJETS ----------------------------
</h6>

<div class="container">
    <div class="row">
        @foreach (var Project in Model.ProjectList)
        {
            string pagelink = "/Project/projectPage/" + Project.Id;
            <div class="col-md-4 d-flex justify-content-center">
                <a href="@pagelink">
                    <div class="single-box">
                        <div class="img-area2"><img src="@Project.Picture" alt="" /></div>
                        <div class="img-text2">
                            <h2>@Project.Name</h2>
                            <p>@Project.Summary</p>
                        </div>
                    </div>
                </a>
            </div>

        }

    </div>
</div>

<br />
<br />

@section Footer
{
    <div class="newsletter-subscribe container">
        <div class="container">
            <div class="intro">
                <h2 class="text-center newsletter">Inscrivez-vous à notre newsletter</h2>
                <p class="text-center">Recevez de nouveaux projets dans votre boite chaque semaine !</p>
            </div>
            <form class="row" method="post">
                <div class="col-md-6"><input class="form-control" type="email" name="email" placeholder="Votre Email"></div>
                <div class="col-md-2"><button class="btn btn-primary" type="button">S'abonner </button></div>
            </form>

        </div>
    </div>
}


<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            /* Toggle between adding and removing the "active" class,
            to highlight the button that controls the panel */
            this.classList.toggle("active");

            /* Toggle between hiding and showing the active panel */
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>